# -*- coding: utf-8 -*-
"""DL_09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qzBMdmzjQGCDTJNsXTJi1HlAmNAYdCJ
"""

!pip install shap

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import shap
import warnings
warnings.filterwarnings('ignore')

url = "https://raw.githubusercontent.com/dsrscientist/dataset1/master/heart_disease.csv"
df  = pd.read_csv(url)

print("HEART DISEASE DATASET INFO")
print(f"Columns         : {list(df.columns)}")

df.head()

X = df.drop('target', axis=1).values
y = df['target'].values

feature_names = list(df.drop('target', axis=1).columns)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# Convert to DataFrame for SHAP plots
X_test_df  = pd.DataFrame(X_test,  columns=feature_names)
X_train_df = pd.DataFrame(X_train, columns=feature_names)

print(f"\nTrain samples  : {X_train.shape[0]}")
print(f"Test samples   : {X_test.shape[0]}")

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu',
                          input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(1,  activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

print("\nTraining MLP Model...")
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

y_pred_prob = model.predict(X_test, verbose=0).flatten()
y_pred      = (y_pred_prob >= 0.5).astype(int)
accuracy    = accuracy_score(y_test, y_pred)

print(f"\nTest Accuracy  : {accuracy*100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred,
      target_names=['No Disease', 'Heart Disease']))

print("\nEvaluating MLP Model on Test Data...")
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

test_loss = loss
test_accuracy = accuracy


plt.figure(figsize=(8, 6))
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

print("\nComputing SHAP Values...")

# Wrap model for SHAP
def model_predict(X):
    return model.predict(X, verbose=0).flatten()

# Use KernelExplainer (works with any black-box model)
# Use small background dataset (50 samples) for speed
background  = X_train[:50]
explainer   = shap.KernelExplainer(model_predict, background)

# Compute SHAP values for test set (use first 50 for speed)
shap_values = explainer.shap_values(X_test[:50], nsamples=100)

print(f"SHAP Values Shape : {np.array(shap_values).shape}")
print("SHAP Values Computed Successfully!")

print("\nPlotting SHAP Summary Plot (Global)...")

plt.figure(figsize=(10, 6))
shap.summary_plot(
    shap_values,
    X_test[:50],
    feature_names=feature_names,
    plot_type='bar',           # Bar chart = global importance
    show=False
)
plt.title('SHAP Feature Importance (Global) - Bar Plot',
          fontweight='bold', fontsize=13)
plt.tight_layout()
plt.show()

print("Plotting SHAP Beeswarm Plot...")

plt.figure(figsize=(10, 6))
shap.summary_plot(
    shap_values,
    X_test[:50],
    feature_names=feature_names,
    plot_type='dot',           # Dot/Beeswarm = direction of impact
    show=False
)
plt.title('SHAP Summary Plot (Beeswarm) - Direction of Impact',
          fontweight='bold', fontsize=13)
plt.tight_layout()
plt.show()

print("\nGenerating SHAP Force Plot for Sample 0...")

# Sample 0
sample_idx   = 0
sample       = X_test[sample_idx]
true_label   = y_test[sample_idx]
pred_prob    = y_pred_prob[sample_idx]
pred_label   = y_pred[sample_idx]

print(f"\nSample {sample_idx} Details:")
print(f"  True Label  : {'Heart Disease' if true_label==1 else 'No Disease'}")
print(f"  Prediction  : {'Heart Disease' if pred_label==1 else 'No Disease'}")
print(f"  Probability : {pred_prob:.4f}")

# Force plot (saved as matplotlib)
shap.force_plot(
    explainer.expected_value,
    shap_values[sample_idx],
    X_test[sample_idx],
    feature_names=feature_names,
    matplotlib=True,
    show=False
)
plt.title(f'SHAP Force Plot - Sample {sample_idx}\n'
          f'True: {"Heart Disease" if true_label==1 else "No Disease"} | '
          f'Pred: {"Heart Disease" if pred_label==1 else "No Disease"} '
          f'({pred_prob:.2f})',
          fontweight='bold', fontsize=11)
plt.show()